### ISSUE TITLE
Export

### ISSUE THREAD

**Issue by TheNoim** [GrabarzUndPartner/nuxt-custom-elements#125]
Hello,

I like the idea of this module. Currently, I export some parts of our page with @vue/cli as WebComponent for some of our partners. However, this is not an ideal solution. I need to maintain two separated configs. Nuxt and vue cli. Now I thought I could replace the vue cli approach with this module. But the thing is, currently I don't see any way to export the generated files. I mean yes, it generates the javascript files in .nuxt. However, it is hard to export them from there. 

I think this module should have some way to generate some kind of bundle in a specific folder. One important thing would be that it has a predictable entry file. The current generated entry file looks like this: name.somehash.js which is not really workflow friendly. I expect an easy way to export the bundle to upload it later to a CDN for example.

**Comment by ThornWalli** [comment]
Hello :)

With a normal Nuxt Build `nuxt build` you would have the bundles under `
dist/nuxt-custom-elements`. 
Currently Nuxt specifies the destination folder, but an option for the destination folder is also possible.

For CDN use, you would need to set `modern` to `false` and define the `webpackOutput` from the module.

```javascript
webpackOutput: {
    filename: '[name].js',
    publicPath: '/'
}
```

So you get predictable entry files without hash.

Alternatively, there is the release.json for each bundle, which can be used to identify the `modern` and `client` build.

**Comment by TheNoim** [comment]
> For CDN use, you would need to set modern to false and define the webpackOutput from the module.

I want to use modern. Is there a way to only disable modern for nuxt-custom-elements?

**Comment by ThornWalli** [comment]
`modern` can now be activated or deactivated. Gives the new [option](https://github.com/GrabarzUndPartner/nuxt-custom-elements#options) `modern` in the module.

The [Webpack output filename](https://github.com/GrabarzUndPartner/nuxt-custom-elements#important-webpackoutput-option) can now be better defined in relation to `modern`. If hashes are needed for caching, they should be defined there.

**Comment by ThornWalli** [comment]
Now gives the option `buildDir`, with it you can define the target directory of the built files.

The target directory is used in `spa` and `universal` mode.

https://github.com/GrabarzUndPartner/nuxt-custom-elements#options
