### ISSUE TITLE
A way to use with Vuetify ?

### ISSUE THREAD

**Issue by BenWaNH** [GrabarzUndPartner/nuxt-custom-elements#151]
Hi, i'm working on Nuxt App combined with Vuetify and i'd wish to build a Widget usable for external websites which reuse already existing components in Nuxt App.
But i don't understand how to implement ....
I've got errors when i tried with build version
"this.$vuetify is undefined"
"TypeError: Cannot read property 'theme' of undefined"

My work look like this for now (components/widgets/widget.vue)
```
<template>
  <div id="widget" @click.prevent.stop>
      <v-card
        color="#385F73"
        flat
        width="50"
        height="200"
        @click="dialog=true"
      >
        Click Here
      </v-card>
  <v-dialog
    v-model="dialog"
    max-width="1200"
  >
    <v-card color="white" id="modalWidget">
      Dialog content
    </v-card>

  </v-dialog>
  </div>
</template>

<script>

import Vuetify, { VCard, VDialog } from 'vuetify/lib'

export default {
  // props: ['title'],
  data () {
    return {
      activeTab: '',
      dialog: false,
    }
  },
  components: {
    VCard,
    VDialog
  },
</script>

<style lang="scss">
  #widget {
    .v-card {
      position: absolute;
      top: 50%;
      transform: translateY(-50%);
    }
  }
</style>
```

It works fine in dev mode with 
```
this.$registerCustomElementsEntry('Widget')
```
and custom element in template layout but not with build command.

Thanks for reading

**Comment by ThornWalli** [comment]
Hello BenWaNH

did you define vuetify Vue registration in the Entry component?
`this.$vuetify` indicates that this is probably still missing. The custom elements bundles are standalone webpack builds and do not get any modules or plugins from Nuxt.

You need to register `Vue.use(Vuetify)` directly in the custom element.

Example: 

```javascript
import Vue from 'vue'
import Vuetify from 'vuetify'
import 'vuetify/dist/vuetify.min.css'

Vue.use(Vuetify)
```

If necessary, move it out to a file and import it into the entry components.
