### ISSUE TITLE
Usage with @nuxt/components

### ISSUE THREAD

**Issue by blocka** [GrabarzUndPartner/nuxt-custom-elements#177]
When I have an auto imported component in my bundle, I get an error `installComponents is not defined`.
Turning off auto import, and manually bringing the component in, things work fine.

**Comment by ThornWalli** [comment]
You can now try it again with the latest release. 
The`installComponent` from `@nuxt/components` was not included in the build.

Now the auto import should work.

**Example**

`GithubCorner`: https://github.com/GrabarzUndPartner/nuxt-custom-elements/blob/master/example/components/organisms/ViewHeader.vue

Preview: https://grabarzundpartner.github.io/nuxt-custom-elements/component-app-bundle/
