### ISSUE TITLE
Error when component uses Vuex Store

### ISSUE THREAD

**Issue by leandrosilvaferreira** [GrabarzUndPartner/nuxt-custom-elements#22]
Cannot read property 'state' of undefined.

It is possible to generate custom elements using vuex store ?

**Comment by ThornWalli** [comment]
Hello leandrosilvaferreira,

You can use the Vuex store, here's an example: https://github.com/GrabarzUndPartner/nuxt-custom-elements/blob/master/example/custom-element/extends/App.vue

The store is defined in the skeleton of the vue component (App). All components contained in the app then have access to the store (this.$store).
