### ISSUE TITLE
webpackConfigs.flat is not a function

### ISSUE THREAD

**Issue by benjick** [GrabarzUndPartner/nuxt-custom-elements#33]
Hey!

Thanks for making this plugin! I'm having some trouble using it though. I'm on Nuxt 2.12.2 and Typescript 3.8.3.

<details>
  <summary>My nuxt-config</summary>

```js
['nuxt-custom-elements', {
  analyzer: true,
  polyfill: true,
  staticPath: '@/static',
  entries: [
    {
      name: 'CoopHandla',
      tags: [
        {
          name: 'CustomElementGrid',
          path: '@/components/apps/Handla',
          options: {
            props: {
              placement: {
                type: String,
                required: true
              },
              placementMore: {
                type: String,
                required: false,
                default: undefined
              },
              rows: {
                type: Number,
                default: 3
              },
            },
          }
        }
      ]
    },
  ],
}],
```
</details>

When I'm running `nuxt generate` I get the following error: `TypeError: webpackConfigs.flat is not a function` which leads me to the following line: https://github.com/GrabarzUndPartner/nuxt-custom-elements/blob/c8dbc69540b511505e09c992bdbf475e02850d25/lib/utils/webpack.js#L33

I'm not really sure where to go from here. I've added `es2019.array` to my tsconfig to rule out that was missing. Any suggestions? Cheers

**Comment by ThornWalli** [comment]
Hello :)

Which node version do you use?
