### ISSUE TITLE
Example of using a component from another origin

### ISSUE THREAD

**Issue by sk-t3ch** [GrabarzUndPartner/nuxt-custom-elements#331]
**Is your feature request related to a problem? Please describe.**
I want to be able to include components created from another project, which is hosted on a different origin. The [examples](https://github.com/GrabarzUndPartner/nuxt-custom-elements-example) only include using components from the same project. 

**Describe the solution you'd like**
I think the IFrames are used to demonstrate that a component has come from elsewhere, however I'd like to see an example with components used from a different origin.

**Describe alternatives you've considered**
I have adapted the example this way and it appears to work but I am unsure if I am doing it correctly:

```
<template>
  <div>
    <client-only>
        <custom-component />
    </client-only>
  </div>
</template>

<script>
import Vue from 'vue';

Vue.config.ignoredElements = [
  'custom-component'
];

export default {
  data () {
    return {
      isDev: process.env.NODE_ENV === 'development',
      base: 'https://another-domain.org/'
    };
  },

  head () {
    const script = [];
    if (!this.isDev) {
      script.push({
        type: 'text/javascript',
        innerHTML: `window.customPublicPath = '${this.base}nuxt-custom-elements/custom-component/';`,
        body: true
      }, {
        type: 'text/javascript',
        src: `${this.base}nuxt-custom-elements/custom-component/custom-component.js`,
        async: true,
        defer: true,
        body: true
      });
    }
    return {
      script,
      __dangerouslyDisableSanitizers: ['script']
    };
  },
  created () {
    this.isDev && this.$registerCustomElementsEntry('CustomComponent');
  }
};
</script>
```

Cheers 💯

**Comment by ThornWalli** [comment]
Hi,

sounds interesting 🙂 Would you perhaps have an example component that lies outside?

Then we could create an example under [nuxt-custom-elements-example](https://github.com/GrabarzUndPartner/nuxt-custom-elements-example), for the integration of external custom elements from an external source.

**Comment by sk-t3ch** [comment]
Hey,

I do have an example component that lies on a domain that I own `https://t3chflicks.org`.  I have [created a PR](https://github.com/GrabarzUndPartner/nuxt-custom-elements-example/pull/10).

**Comment by ThornWalli** [comment]
Done! :)
