### ISSUE TITLE
Including generated components in an external html for testing in dev mode.

### ISSUE THREAD

**Issue by juanfernandoe** [GrabarzUndPartner/nuxt-custom-elements#34]
Hi there.

Thank you for this amazon work.

Is there an URL in dev mode where the generated component (.js) is exposed to be included in an external HTML page?

something like 
http://localhost:3000/nuxt-custom-elements/my-components.js

**Comment by ThornWalli** [comment]
Hi,
In Development Mode the target files are in the Webpack runtime. Therefore, they cannot be retrieved externally.
