### ISSUE TITLE
Generating components with baked-in async `data`

### ISSUE THREAD

**Issue by SteveFromAccounting** [GrabarzUndPartner/nuxt-custom-elements#345]
Is it possible to generate components with async data that is baked in? For a somewhat contrived example, I'd have a `<FavoriteDog />` component built out as a template like:

```vue
<template>
  <h1>{{ dogName }}</h1>
</template>
<script>
export default {
  data () {
    return {
      dogName: null
    };
  },
};
</script>
<style scoped>
h1 { color: red }
</style>
```

And ideally, I'd want to have a bunch of web components output per dog name, like: `<dog-spot></dog-spot>`, `<dog-fido></dog-fido>`

Of course in the example above, realistically it would be a large amount of JSON data from an API that someone using your components wouldn't have access to, and it wouldn't be nearly as simple as just inputting a name via a web component prop when they use it like `<dog name="fido"></dog>`.

The `props` option unfortunately only outputs the data into the (nuxt) generated HTML template, so I'm not able to expect people using my components to pass in this massive JSON payload every time they use my component. I read about using the `fetch()` hook in Nuxt.js, but that unfortunately doesn't seem to do the trick with your plugin (e.g., 

```vue

<!-- ... -->

<script>
export default {
  // ...
  async fetch() {
    const dogs = await this.$axios.$get(`https://api.nuxtjs.dev/dogs`)

    const dogOne = dogs[0]

    this.dogName = dogOne.name;

  },
  fetchOnServer: true,
  // ...
};
```

**Comment by SteveFromAccounting** [comment]
Would the main option I have to build something like you have, and turn the component *.vue file into a Handlebars (or whatever) template, like

```js
// ...
export default {
  data () {
    return {
      dogName: <%= asyncPayload %>
    };
  },
};
// ...
```

**Comment by ThornWalli** [comment]
Close the issue for now, but can be reopened if used.
