### ISSUE TITLE
webpack chunk optimization

### ISSUE THREAD

**Issue by markuzzi** [GrabarzUndPartner/nuxt-custom-elements#346]
**Is your feature request related to a problem? Please describe.**
The bundles I create with nuxt-custom-elements grew over time, especially because of large libraries like vuetify.
Thus, I want to optimize bundling and create chunks with webpack.
This can be achieved with the async flag, however, this only creates chunks for the components, not for the libs.

**Describe the solution you'd like**
I want to be able to configure webpack optimization.

**Solution**
I added another option called "webpackOptimization", e.g.
``` js
webpackOptimization: {
    splitChunks: {
      automaticNameDelimiter: '-',
      minChunks: 1,
      minSize: 100_000,
      chunks: 'all',
      cacheGroups: {
        vuetify: {
          test: /vuetify/,
          name: 'ui-framework',
          chunks: 'all',
          priority: 10,
          enforce: true
        },
      },
    }
  }
```

To make this happen, `utils/webpack.js` has to be adapted in lines 88:91
``` js
    optimization: Object.assign({
      // minimize: false,
      runtimeChunk: false
    }, options.webpackOptimization),
```

Also, to have meaningful names for chunks if the async flag is used for tags, `templ/entry.js` line 26 should be changed to
```
 %><%= `Vue.customElement('${name}', () => { return import(/* webpackChunkName: "${name}" */ '${path}').then(module => (typeof module.default === 'function' ? (new module.default).$options : module.default) ); }, ${options});\n` %><%
```

Would that be a valuable extension to you great module?

Thanks!

**Comment by ThornWalli** [comment]
Hi ,

sounds good :)

If you like you can make a pull request.

**Comment by markuzzi** [comment]
Alright, I will do some additional testing and documentation for the PR.
