### ISSUE TITLE
Switch to the official wc implementation

### ISSUE THREAD

**Issue by TheNoim** [GrabarzUndPartner/nuxt-custom-elements#347]
Currently the project works with vue-custom-element.

However, even in the readme of vue-custom-element they refer to the now official webcomponents implementation: https://github.com/vuejs/vue-web-component-wrapper

Or maybe an option to choose between both options. I think, the support for vue 3 will be better in the future with the official implementation.

**Comment by rmarmitt** [comment]
That would be fantastic

**Comment by ThornWalli** [comment]
I have opened an issue which covers this topic. https://github.com/GrabarzUndPartner/nuxt-custom-elements/issues/433

Switching to Bridge or Nuxt 3 will allow the use of Vue 3.
