### ISSUE TITLE
Not working with extractCSS

### ISSUE THREAD

**Issue by hieunhit** [GrabarzUndPartner/nuxt-custom-elements#354]
**Describe the bug**
When i turned on `extractCSS`, this module is not working
```
/nuxt-custom-elements-example-main/node_modules/extract-css-chunks-webpack-plugin/dist/index.js:70
    const resource = this._identifier.split('!').pop();
```

**To Reproduce**
`extractCSS: true`

**Expected behavior**
Need support `extractCSS` to generate css file

**Comment by ThornWalli** [comment]
Hello @hieunhit,

Now it should also work with `extractCSS`.
