### ISSUE TITLE
Generate only a single lang?

### ISSUE THREAD

**Issue by tim-kilian** [GrabarzUndPartner/nuxt-custom-elements#435]
I use nuxt-i18n in my project and when I generate my final component.js every lang file of any language is in the resulting js file. I would like to split it, so that I have different js for different languages. Example `component-en.js` , `component-de.js`. Is this possible and how?

**Comment by ThornWalli** [comment]
Hello @tim-kilian,

Have you looked at the [example](https://github.com/GrabarzUndPartner/nuxt-custom-elements-example/tree/main/examples/vue-i18n) in relation to `i18n`?

You need `vue-i18n` in the entry you want to export.

- https://github.com/GrabarzUndPartner/nuxt-custom-elements-example/blob/main/examples/vue-i18n/plugins/vueI18n.js
- https://github.com/GrabarzUndPartner/nuxt-custom-elements-example/blob/main/examples/vue-i18n/entries/VueI18n.vue

There you have free decision what languages will come in ;)

Means every plugin which is included in `nuxt`, must be specified in the entry of the custom element. 

Background is that each entry represents a separate VueApp.

**Comment by tim-kilian** [comment]
Hej. Yes I did it exactly like that. And every time he includes every lang file in the directory, even if it is not mentioned in the plugin / entry.

**Comment by ThornWalli** [comment]
Do you have an import like this?

```js
import('/lang/' + lang + '.js')
```

Alternatively you can also show your plugin what you have built in the entry? 🙂

**Comment by ThornWalli** [comment]
Close the issue for now, but can be reopened if used.
