### ISSUE TITLE
[Help] Fonts are not loaded correctly

### ISSUE THREAD

**Issue by rmarmitt** [GrabarzUndPartner/nuxt-custom-elements#444]
We are creating some web components using this awesome lib.

But I'm stuck in a problem...

It looks like the fonts are not properly loaded when generating the component build.

What i've tried so far:

Load fonts in entry
![image](https://user-images.githubusercontent.com/56549636/164066832-ee400794-2676-42c1-95b7-cecf638b04bc.png)

This not work. When I include the generated bundle into HTML pages, an error appears in network
![image](https://user-images.githubusercontent.com/56549636/164067049-d7a243f7-9e54-4363-9ce7-f2b7c2716aac.png)

How can we add font files to generated bundle?

Any suggestion is welcome

**Comment by rmarmitt** [comment]
In time: Is it possible to add a loader in webpack? I believe that would solve it. Eg:

![image](https://user-images.githubusercontent.com/56549636/164067921-abc90748-4b54-452f-9504-ef075b2058fa.png)

**Comment by ThornWalli** [comment]
Hello @rmarmitt,

I have tested, everything seems to work.

This is how it looks like in my code https://github.com/GrabarzUndPartner/nuxt-custom-elements/blob/feature/webfont/example/components/Example.vue

![image](https://user-images.githubusercontent.com/8287751/164077844-16b9fa11-fd65-40db-a848-39af036fe21d.png)

|Build|Generate|
|--|---|
|![image](https://user-images.githubusercontent.com/8287751/164077252-02abd68e-722f-4b37-9243-3b8959490803.png)|![image](https://user-images.githubusercontent.com/8287751/164076280-21808dfd-8d5d-4f91-a52b-4c085efd5b49.png)|


You don't really need to extend a webpack configuration, here it is used by `nuxt` and this should be sufficient.

But is a good point with extending the webpack configuration from outside. 
This would then be entry based, each entry has its own webpack configuration.

What files are in your `dist` folder? Can you maybe show the `nuxt.config`?

**Comment by rmarmitt** [comment]
Hi @ThornWalli

Thanks for the answer.

The build:
![image](https://user-images.githubusercontent.com/56549636/164078361-80b2535b-14c2-4323-84f0-d171286263cb.png)

The generate:
![image](https://user-images.githubusercontent.com/56549636/164078487-ff06ed6d-78da-4056-b53e-c5a348956663.png)

The nuxt.config:
![image](https://user-images.githubusercontent.com/56549636/164078660-0fd7e451-5498-4bed-9f9b-c9281edeecb9.png)


In fact, the fonts are added in build. But, when I load the script, I ran into problem.

This is my script.js implementation of web component
![image](https://user-images.githubusercontent.com/56549636/164078862-e5fd7823-b54a-47b3-9c14-24d24f9dfb6d.png)

And in .vue file, I have:
<wc-example :token="token" :locale="$root.$i18n.locale" />

**Comment by rmarmitt** [comment]
The problem is that the browser is trying to load the fonts locally.

For example:
![image](https://user-images.githubusercontent.com/56549636/164079769-4d8558ae-a729-4595-ae56-71ffe948f7d8.png)

This request should come from [https://dev.valid-url/projet/web-components/example/fonts/....], right?

**Comment by ThornWalli** [comment]
I think I know what your problem is. If the script is included externally and the source is not in the root, you still need a `publicPath` in Webpack, something like a basepath for the webpack resources.

https://nuxt-custom-elements.grabarzundpartner.dev/options#publicpathinject

Try something like this, alternatively you can define it on the target page like in the link.

```javascript
{
  publicPathInject: () => 'https://dev.valid-url/project/web-components/example'
}
```

Just ask me if this would also be useful for the individual entries...

**Comment by rmarmitt** [comment]
Hmm...

I think I'm forgetting something.

My `customPublicPath` is set, and I can see it through console.log for example.

![image](https://user-images.githubusercontent.com/56549636/164090277-39adc129-b2c6-409c-8361-c9726eda777d.png)

![image](https://user-images.githubusercontent.com/56549636/164090370-6e6b4353-c4c1-4eac-8f2d-02b4205341ab.png)

But the fonts keep loading locally.

![image](https://user-images.githubusercontent.com/56549636/164090467-c57883f9-ee8e-4568-84a9-6ecd3040c3d6.png)

**Comment by ThornWalli** [comment]
Now it clicked. Mmhhh what now 🙃

Must think about it, seems to be missing in the CSS.

Come there just also first on something like that...
https://medium.com/@raviroshan.talk/webpack-understanding-the-publicpath-mystery-aeb96d9effb1

As a workaround you could use a Base64 as font ;)

**Comment by rmarmitt** [comment]
I don't think using base64 for fonts is a good workaround. It looks like it's going to be pretty slow. :s

In fact, it would be better if I could just ignore these fonts in the build. It is possible?

It seems that even if I don't include the CSS in the entry, the fonts are automatically included. I didn't find the reason 🤯

**Comment by ThornWalli** [comment]
@rmarmitt I think I have a solution for you, for the first it should be enough 🙂

![image](https://user-images.githubusercontent.com/8287751/164102468-3d85795e-ed92-43d2-a7a8-76f151d4d088.png)


```
webpack: {
  output: {
    publicPath: 'http://localhost:3000/nuxt-custom-elements/example/'
  }
},
```

**Comment by rmarmitt** [comment]
OMG! It worked

Amazing. Thank you for your help.

I hope to bring a production use case of this solution soon 🚀

**Comment by rmarmitt** [comment]
If anyone is facing this issue and needs a dynamic publicPath, here is a solution:

https://www.npmjs.com/package/webpack-dynamic-public-path

`
webpack  : {
  output: {
    publicPath: "publicPathPlaceholder"
  },
  plugins: [
    new WebpackDynamicPublicPathPlugin({
      externalPublicPath: "window.customPublicPath"
     })
  ]
}
`

**Comment by ThornWalli** [comment]
@rmarmitt Interesting solution :)

I will include this in the documentation.

**Comment by ThornWalli** [comment]
@rmarmitt In the `beta` is now already once adjustments to the Webpack configuration and the publicPathInject. The `publicPathInject` is completely removed and will be solved via the plugin solution.

- https://github.com/GrabarzUndPartner/nuxt-custom-elements/blob/beta/docs/content/en/usage.md#webpack-public-path
- https://github.com/GrabarzUndPartner/nuxt-custom-elements/blob/beta/docs/content/en/options.md#entry
