### ISSUE TITLE
[#ask] How to configure output css name

### ISSUE THREAD

**Issue by sibiru** [GrabarzUndPartner/nuxt-custom-elements#467]
**Is your feature request related to a problem? Please describe.**
Actually this is not feature request just ask how to configure output fixed css name?

**Comment by ThornWalli** [comment]
Hello @sibiru,

do not really understand your question. 🙂

What exactly do you mean by set css name output?

With the entry it is up to you whether you work with global, scoped or shadow CSS.

**Comment by sibiru** [comment]
When I create custom component with custom tailwind styles, it will generate css file right?  
for example in my screenshot below `bbde1fe,css`  
how I make the css file to have fixed name for example; `flik-button.css`  
  
![](https://user-images.githubusercontent.com/114682/168491613-3d73f569-47b3-416b-bd85-2cc606dfdba2.png)

**Comment by ThornWalli** [comment]
You could try this out. 
https://nuxtjs.org/docs/configuration-glossary/configuration-build/#filenames

Alternatively you can try to modify this in the webpack loader in the entry settings. 
https://nuxt-custom-elements.grabarzundpartner.dev/options#more-about-webpackextend

**Comment by ThornWalli** [comment]
Close the issue for now, but can be reopened if used.
