### ISSUE TITLE
Strange behavior with multiple external applications

### ISSUE THREAD

**Issue by rmarmitt** [GrabarzUndPartner/nuxt-custom-elements#523]
Hello, I would like help with a strange behavior that is happening in an application.

The main application makes use of 2 web components, each of which comes from external applications. The external applications are "academic services" and "messages".

When I access the page in the main application, which will load the web component of the "academic services" application, everything works perfectly. See the print of the loaded scripts:

![image](https://github.com/GrabarzUndPartner/nuxt-custom-elements/assets/56549636/fd667351-b009-40d2-a4a5-1f1bd1a7596b)

So when I navigate to the "messages" page, the scripts seems to be partially loaded and I get this error in the console:

![image](https://github.com/GrabarzUndPartner/nuxt-custom-elements/assets/56549636/73aeeedd-7cc0-4315-85ba-e9987bd7bd59)

![image](https://github.com/GrabarzUndPartner/nuxt-custom-elements/assets/56549636/fcf2b4b8-2409-43a7-bc19-0a8258f2af83)

Notice that only chunk "5" was loaded. Now, if I reload this page, all chunks are loaded and everything works perfectly:

![image](https://github.com/GrabarzUndPartner/nuxt-custom-elements/assets/56549636/435da36a-4075-4c74-a945-a80ed51417b2)

I tested several configurations (use of hashes in chunks, disabled polyfill, etc.) but nothing seems to work. The impression is that it is reusing previously downloaded chunks (As it only downloaded chunk 5. After the refresh, all chunks are downloaded).

This is the "academic services" configuration:
```js
customElements: {
  buildDir : 'dist/web-components',
  entries  : [
    {
      name: 'default',
      webpackExtend(config) {
        config.output = {
          ...config.output,
          publicPath    : 'publicPathPlaceholder',
          filename      : `[name].academic-services.js`,
          chunkFilename : '[name].[hash].js'
        };

        config.plugins = [
          ...config.plugins,
          new (require('webpack-dynamic-public-path'))({
            externalPublicPath: `window.acedemicServicesCustomPublicPath`
          })
        ];
      },
      tags: [
        {
          name  : 'WcMainAs',
          path  : '@/entries/default/main-as',
          async : true,
          options() {
            return {
              props          : ['token'],
              destroyTimeout : null,
              vueInstanceCreatedCallback() {
                window.dispatchEvent(new CustomEvent('wcVueInstanceCreated'));
              }
            };
          }
        }
      ]
    }
  ]
}
```

And this one is from "messages":
```js
customElements: {
  buildDir : 'dist/web-components',
  entries  : [
    {
      name: 'default',
      webpackExtend(config) {
        config.output = {
          ...config.output,
          publicPath    : 'publicPathPlaceholder',
          filename      : `[name].messages.js`,
          chunkFilename : '[name].[hash].js'
        };

        config.plugins = [
          ...config.plugins,
          new (require('webpack-dynamic-public-path'))({
            externalPublicPath: `window.messagesCustomPublicPath`
          })
        ];
      },
      tags: [
        {
          name  : 'WcMainMs',
          path  : '@/entries/default/mainMs',
          async : true,
          options() {
            return {
              props          : ['token'],
              destroyTimeout : null,
              vueInstanceCreatedCallback() {
                window.dispatchEvent(new CustomEvent('wcVueInstanceCreated'));
              }
            };
          }
        }
      ]
    }
  ]
}
```

Any suggestion is welcome, and thanks again 😄

**Comment by ThornWalli** [comment]
Hello @rmarmitt ,

think I forgot something 😉

I guess it's because of the different `webpack` instances, they currently load the chunks on the same way.

For this I had used in the old, the `jsonpFunction` function. 
https://github.com/GrabarzUndPartner/nuxt-custom-elements/blob/c940e77667e79f17ff57baf638edb16a8ae3fb9c/lib/utils/webpack.js#L127

Now the equivalent for webpack@5 has to be found.
https://github.com/GrabarzUndPartner/nuxt-custom-elements/blob/f4065316964d6ad8fbb3ee8ddc585993e7385a20/src/utils/webpack.mjs#L53-L69

I'll have a look at it 🙂

**Comment by rmarmitt** [comment]
Hello @ThornWalli, how are you?

Nice. Just remembering that I'm using nuxt@2, and currently using version 1.9.1 of nuxt-custom-elements.

From the snippet you provided, it looks like it's on version 2.0.0-beta.13. Am I missing something?

**Comment by ThornWalli** [comment]
🙃 I was probably a little further along then 😉

Yes then the problem is really a bit strange, what hides in the line where the `call` can not be called?

The stack is not enough.

**Comment by rmarmitt** [comment]
> @rmarmitt Could it even be your problem?
> 
> The `jsonpFunction` gets the `entryName` (e.g. `default`).
> 
> Both have the same... 😉
> 
> Question would be what to take as an alternative when it comes to uniqueness the `jsonpFunction` name.

So what it looks like is that I can't have two different (and independent) applications with the same `customElements.entries[0].name`?

Because if you look at the `filename` it is unique, eg:

Academic services will be:
`[name].messages.js` => `default.academic-services.js`

And messages will be:
`[name].messages.js` => `default.messages.js`

**Comment by rmarmitt** [comment]
Basically this is my architecture

![image](https://github.com/GrabarzUndPartner/nuxt-custom-elements/assets/56549636/60546b4c-8492-43d3-b35f-ca24eee9f92f)

Here is where the `call` cannot be called :sweat_smile:

![image](https://github.com/GrabarzUndPartner/nuxt-custom-elements/assets/56549636/52729307-99d1-4b3b-a608-4f85c0d5fad2)

**Comment by ThornWalli** [comment]
@rmarmitt You can set the `jsonpFunction` in your `webpackExtend `. 
That should solve the problem.

https://github.com/GrabarzUndPartner/nuxt-custom-elements/blob/c940e77667e79f17ff57baf638edb16a8ae3fb9c/lib/utils/webpack.js#L120-L137

**Comment by rmarmitt** [comment]
Hi @ThornWalli

Yes! It worked like a charm.

So basically, we can't have the same `entry` in different applications or if that's the case, we need to specify the `jsonpFunction` to prevent name collision.

Thanks a lot again for the help. 🚀
